// results/vue/src/views/search-view.vue
<template>
  <div id="search-view">
    <loading-bar :visible="loading"></loading-bar>
    <div class="card hollow">
      <search-box></search-box>
    </div>
    <div class="card hollow" v-show="!results.length && noResults">
      <p><em>No results for &laquo;<span v-text="searchTitle"></span>&raquo;</em></p>
    </div>
    <div class="card hollow" v-show="results.length">
      <p><em>Search results for &laquo;<span v-text="searchTitle"></span>&raquo;</em></p>
      <ul class="search__results">
        <search-result v-for="r in results" :movie="r"></search-result>
      </ul>
    </div>
    <div class="card hollow" v-show="results.length < totalResults && results.length">
      <a href="#" class="more" @click="getMoreResults">Load more results</a>
    </div>
  </div>
</template>

<script>
import search from '../services/search';
import searchBox from '../components/search-box.vue';
import searchResult from '../components/search-result.vue';
import loadingBar from '../components/loading-bar.vue';

let persistData = null;

export default {
  components: {
    searchBox,
    searchResult,
    loadingBar
  },
  data () {
    return {
      loading: true,
      searchTitle: '',
      results: [],
      totalResults: 0,
      pageResults: 0,
      noResults: false
    }
  },
  methods: {
    getMoreResults(e) {
      e.preventDefault();
      this.loading = true;
      search(this.searchTitle, ++this.pageResults)
      .then(data => {
        this.results = this.results.concat(data.Search);
        this.loading = false;
      });
    }
  },
  mounted() {
    this.$nextTick(_ => this.loading = false);
  },
  beforeRouteEnter(to, _from, next) {
    next(view => {
      if (persistData) {
        for (let p in persistData) {
          view.$data[p] = persistData[p];

        }
      }
    });
  },
  beforeRouteLeave(to, _from, next) {
    if (this.results.length) {
      persistData = {
        searchTitle: this.searchTitle,
        results: this.results,
        totalResults: this.totalResults,
        pageResults: this.pageResults,
        noResults: this.noResults
      }
    }
    next();
  }
}
</script>

<style lang="less" scoped>
@import '../styles/variables.less';

.search__results {
  list-style: none;
  margin: 0;
  padding: 0;
}

.more {
  color: @accent;
  display: block;
  text-align: center;
  text-decoration: none;
  .label();
}
</style>

// results/react/src/views/search-view.js
import React, { Component } from 'react';
import search from '../services/search';

// components
import { Link } from 'react-router';
import LoadingBar from '../components/loading-bar.js';
import Card from '../components/card.js';
import SearchBox from '../components/search-box.js';
import SearchResult from '../components/search-result.js';

// styles
import styles from '../styles/search-view.less';

let persistData = null;

export default class SearchView extends Component {
  constructor(props) {
    super(props);

    this.state = {
      pageResults: 1,
      results: [],
      searchTitle: '',
      totalResults: 0,
      noResults: true
    };

    // bind event context
    this.resetData = this.resetData.bind(this);
    this.setTitle = this.setTitle.bind(this);
    this.setResults = this.setResults.bind(this);
    this.getMoreResults = this.getMoreResults.bind(this);
  }
  resetData() {
    this.setState({ results: [] });
    this.setState({ pageResults: 1 });
  }
  setTitle(title) {
    this.setState({ searchTitle: title});
  }
  setResults(results, total) {
    this.setState({ results: results });
    this.setState({ noResults: !!results.length });
    this.setState({ totalResults: total });
  }
  getMoreResults(e) {
    e.preventDefault();

    this.props.startLoading();

    search(this.state.searchTitle, this.state.pageResults + 1)
      .then(data => {
        const results = this.state.results.concat(data.Search);

        this.setState({ results });
        this.setState({ pageResults: ++this.state.pageResults });

        this.props.stopLoading();
      });
  }
  componentWillUnmount() {
    persistData = {
      results: this.state.results,
      totalResults: this.state.totalResults
    };
  }
  componentWillMount() {
    if (persistData) {
      this.setState({ results: persistData.results });
      this.setState({ totalResults: persistData.totalResults });
    }
  }
  render() {
    const results = this.state.results;

    return (
      <div>
        <Card hollow>
          <SearchBox
            resetParentData={ this.resetData }
            setParentTitle={ this.setTitle }
            setParentResults={ this.setResults }
            startLoading={ this.props.startLoading }
            stopLoading={ this.props.stopLoading }
          ></SearchBox>
        </Card>

        <Card hollow>
          <p hidden={ !this.state.results.length }>
            <em>Search results for &laquo;{ this.state.searchTitle }&raquo;</em>
          </p>
          <p hidden={ this.state.noResults }>
            <em>No search results for &laquo;{ this.state.searchTitle }&raquo;</em>
          </p>
          <ul className={ styles.search__results }>
          {
            results.map((result, index) => {
              if (result && result.imdbID ) {
                const id = `${ result.imdbID }-${ index }`;

                return (
                  <SearchResult key={ id } data={ result }></SearchResult>
                );
              }
            })
          }
          </ul>
        </Card>

        <Card hollow
          hidden={ !(this.state.results.length < this.state.totalResults && this.state.results.length) }>
          <a href="#" className={ styles.more } onClick={ this.getMoreResults }>
            Load more results</a>
        </Card>
      </div>
    );
  }
};
