// results/react/src/views/movie-view.js
import React, { Component } from 'react';
import movie from '../services/movie';

// components
import { Link } from 'react-router';
import Card from '../components/card.js';
import MovieBox from '../components/movie-box.js';

// styles
import styles from '../styles/movie-view.less';

export default class MovieView extends Component {
  constructor(props) {
    super(props);

    this.state = {
      loaded: false,
      movie: {}
    }
  }
  componentDidMount() {
    this.props.startLoading();

    // fetch movie data
    movie(this.props.params.id)
     .then(data => {
       this.setState({ movie: data });
       this.setState({ loaded: true });

       this.props.stopLoading();
     });
  }
  render() {
    const classes = this.state.loaded ? `${ styles.movie } ${ styles.loaded }` : `${ styles.movie }`;

    return (
      <div className={ classes }>
      <Card>
        <MovieBox loaded={ this.state.loaded } data={ this.state.movie }></MovieBox>
      </Card>
      </div>
    );
  }
};

// results/vue/src/views/movie-view.vue
<template>
  <div class="card movie" :class="{ 'loaded': loaded }">
    <movie-box :movie="movie"></movie-box>
</template>

<script>
import movie from '../services/movie';
import movieBox from '../components/movie-box.vue';

export default {
  components: {
    movieBox
  },
  data() {
    return {
      movie: {}
    };
  },
  props: {
    loaded: {
      type: Boolean,
      default() {
        return false;
      }
    }
  },
  attached() {
    this.$router.app.loading = true;
    // fetch movie data
    movie(this.$route.params.id)
     .then(data => {
       this.movie = data;
       this.loaded = true;
       this.$router.app.loading = false;
     });
  }
}
</script>

<style lang="less" scoped>
@import '../styles/variables.less';

.movie {
  line-height: 1.5;
  opacity: 0;
  overflow: hidden;
  transition: all .25s ease;

  &.loaded {
    opacity: 1;
  }
}
</style>
