// results/react/src/views/search-view/search-view.js
import React, { Component } from 'react';
import search from '../../services/search';

import Card from '../../components/card/card.js';
import SearchBox from '../../components/search-box/search-box.js';
import SearchResult from '../../components/search-result/search-result.js';

import styles from './search-view.less';

export default class SearchView extends Component {
  constructor(props) {
    super(props);

    this.state = {
      pageResults: 1,
      results: [],
      searchTitle: '',
      totalResults: 0,
      noResults: true
    };

    this.resetData = this.resetData.bind(this);
    this.setTitle = this.setTitle.bind(this);
    this.setResults = this.setResults.bind(this);
    this.getMoreResults = this.getMoreResults.bind(this);
  }

  resetData() {
    this.setState({ results: [] });
    this.setState({ pageResults: 1 });
  }

  setTitle(title) {
    this.setState({ searchTitle: title});
  }

  setResults(results, total) {
    this.setState({ results: results });
    this.setState({ noResults: !!results.length });
    this.setState({ totalResults: total });
  }

  getMoreResults(e) {
    e.preventDefault();
    search(this.state.searchTitle, this.state.pageResults + 1)
      .then(data => {
        const results = this.state.results.concat(data.results);
        const pageResults = data.page;

        this.setState({ results, pageResults });
      });
  }

  componentWillUnmount() {
    const persistData = {
      searchTitle: this.state.searchTitle,
      results: this.state.results,
      totalResults: this.state.totalResults
    };
  }

  render() {
    const results = this.state.results;

    return (
      <div>
        <Card hollow>
          <SearchBox
            resetParentData={this.resetData}
            setParentTitle={this.setTitle}
            setParentResults={this.setResults}
          />
        </Card>
        <Card hollow>
          <p hidden={!this.state.results.length}>
            <em>Search results for &laquo;{this.state.searchTitle}&raquo;</em>
          </p>
          <p hidden={this.state.noResults}>
            <em>No search results for &laquo;{this.state.searchTitle}&raquo;</em>
          </p>
          <ul className={styles.search__results}>{results.map(renderResult)}</ul>
        </Card>

        <Card hollow
          hidden={!(this.state.results.length < this.state.totalResults && this.state.results.length)}>
          <a href="#" className={styles.more} onClick={this.getMoreResults}>
            Load more results</a>
        </Card>
      </div>
    );
  }
};

function renderResult(result) {
  if (result !== undefined) {
    return (
      <SearchResult
        key={ result.id }
        data={ result }
      />
    );
  }
}

// results/vue/src/views/search-view.vue
<template>
  <div class="card hollow">
    <search-box></search-box>
  </div>
  <div class="card hollow" v-show="!results.length && noResults">
    <p><em>No results for &laquo;<span v-text="searchTitle"></span></em>&raquo;</p>
  </div>
  <div class="card hollow" v-show="results.length">
    <p><em>Search results for &laquo;<span v-text="searchTitle"></span></em>&raquo;</p>
    <ul class="search__results">
      <search-result v-for="r in results" :movie="r"></search-result>
    </ul>
  </div>
  <div class="card hollow" v-show="results.length < totalResults && results.length">
    <a href="#" class="more" @click="getMoreResults">Load more results</a>
  </div>
</template>

<script>
import search from '../services/search';
import searchBox from '../components/search-box.vue';
import searchResult from '../components/search-result.vue';

let persistData = null;

export default {
  components: {
    searchBox,
    searchResult
  },
  data () {
    return {
      searchTitle: '',
      results: [],
      totalResults: 0,
      pageResults: 0,
      noResults: false
    }
  },
  methods: {
    getMoreResults(e) {
      e.preventDefault();
      this.$router.app.loading = true;
      search(this.searchTitle, ++this.pageResults)
      .then(data => {
        this.results = this.results.concat(data.Search);
        this.$router.app.loading = false;
      });
    }
  },
  ready() {
    this.$router.app.loading = false;
  },
  route: {
    activate() {
      this.$data = persistData ? persistData : this.$data;
    },
    deactivate() {
      persistData = this.results.length ? this.$data : null;
    }
  }
}
</script>

<style lang="less" scoped>
@import '../styles/variables.less';

.search__results {
  list-style: none;
  margin: 0;
  padding: 0;
}

.more {
  color: @accent;
  display: block;
  text-align: center;
  text-decoration: none;
  .label();
}
</style>
