// results/react/src/views/movie-view.js
import React, { Component } from 'react';
import movie from '../services/movie';

// components
import { Link } from 'react-router';
import Card from '../components/card.js';
import MovieBox from '../components/movie-box.js';

// styles
import styles from '../styles/movie-view.less';

export default class MovieView extends Component {
  constructor(props) {
    super(props);

    this.state = {
      loaded: false,
      movie: {}
    }
  }
  componentDidMount() {
    this.props.startLoading();

    // fetch movie data
    movie(this.props.params.id)
     .then(data => {
       this.setState({ movie: data });
       this.setState({ loaded: true });

       this.props.stopLoading();
     });
  }
  render() {
    const classes = this.state.loaded ? `${ styles.movie } ${ styles.loaded }` : `${ styles.movie }`;

    return (
      <div className={ classes }>
      <Card>
        <MovieBox loaded={ this.state.loaded } data={ this.state.movie }></MovieBox>
      </Card>
      </div>
    );
  }
};

// results/angular/src/app/views/movie-view.ts
import { Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { MovieService } from '../services/movie-service';

@Component({
  selector: 'movie-view',
  styleUrls: [ './movie-view.less' ],
  templateUrl: './movie-view.html'
})

export class MovieView {
  loaded: boolean;
  data: any;

  constructor(private route: ActivatedRoute, public movie: MovieService) {}

  ngOnInit() {
    this.loaded = false;

    this.route.params.subscribe(params => {
      this.movie.getById(params['id'])
        .subscribe(data => {
          this.data = data;
          this.loaded = true;
        });
    });
  }
}
